
from django.shortcuts import render,redirect
from django.http import HttpResponse
from .models import*
from django.contrib import messages
from deliveryapp.models import*
from restapp.models import*
import string,random 
from fooddelivery.settings import EMAIL_HOST_USER
from django.core.mail import send_mail

# Create your views here.

#def index(request):
    #return render(request,'index.html')
def adlogin(request): #login
 if request.method=='POST':
        try:
            adname=request.POST['adname']
            adpass=request.POST['adpass']
           
            check=adminreg.objects.get(adname=adname,adpass=adpass)
            request.session['id']=check.id
            request.session['adname']=check.adname
            return redirect('adminhome')
        except adminreg.DoesNotExist as e:
            messages.info(request,'Invalid User')
 return render(request,'admin/adlogin.html')
        
    

def adsignup(request): #sign in
    if request.method=='POST':
      adname=request.POST['adminname']
      adpass=request.POST['adpass']
      repass=request.POST['repass']
      if adpass==repass:
        if adminreg.objects.filter(adname=adname).exists():
           n="name"
           messages.info(request,'user already exists')
           return render(request,'admin/adsignup.html',{'n':n})

        else:
           saveval=adminreg(adname=adname,adpass=adpass)
           print("user created")
           saveval.save()
           return redirect('adlogin')
      else:
         p="pass"
         messages.info(request,'Password not same !!') 
         return render(request,'admin/adsignup.html',{'p':p})
 
    return render(request,'admin/adsignup.html')



def adminhome(request):
   
    return render(request,'admin/adminhome.html')

#--------------------------------------------------Delivery -------------------------------------------------------------

def viewdel(request):   #view delivery boy details 
   delall=delvreg.objects.all()
   context={
      'delall':delall
   }
   return render(request,'admin/viewdel.html',context)

def send_email(request,id):       # send email to delivery boy
   delall=delvreg.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for i in range(8))
        delvreg.objects.filter(id=id).update(dpass=password)
        
        message = '''Welcome to OurWorkGem site.
        you can change automatically generated password after login to your profile
        Steps you should follow for changing password:
        1) Login your profile with autogenerated password
        2) After click on the profile button in the home page
        3) In that profile click on the change password button then you change the password
        You can login with this password : ''' +format(password)
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'admin/send_email.html',{'delall':delall})

def delapprove(request,id):    #approve delivery boy
   delvreg.objects.filter(id=id).update(approve=True)
   delall=delvreg.objects.all()
   context={
      'delall':delall
   }
   return render(request,'admin/viewdel.html',context)



#---------------------------------------------------Restaurant----------------------------------------------------------------


def viewrest(request):   #view Restaurantrestuarent details 
   restall=restreg.objects.all()
   context={
      'restall':restall
   }
   return render(request,'admin/viewrest.html',context)

def send_restemail(request,id):       # send email to Restaurant boy
   restall=restreg.objects.get(id=id)
   #sub = forms.Subscribe()
   if request.method == 'POST':
        sub = request.POST['email']
        name= request.POST['name']
        subject = 'Hi, '+format(name) 
        recepient = str(sub)
      
        # get random password pf length 8 with letters, digits, and symbols
        characters = string.ascii_letters + string.digits + string.punctuation
        password = ''.join(random.choice(characters) for i in range(8))
        restreg.objects.filter(id=id).update(restpass=password)
        
        message = '''Welcome to OurWorkGem site.
        you can change automatically generated password after login to your profile
        Steps you should follow for changing password:
        1) Login your profile with autogenerated password
        2) After click on the profile button in the home page
        3) In that profile click on the change password button then you change the password
        You can login with this password : ''' +format(password)
        send_mail(subject, 
            message, EMAIL_HOST_USER, [recepient], fail_silently = False)
   return render(request,'admin/send_restemail.html',{'restall':restall})

def restapprove(request,id):    #approve Restauran boy
   restreg.objects.filter(id=id).update(approve=True)
   restall=restreg.objects.all()
   context={
      'restall':restall
   }
   return render(request,'admin/viewrest.html',context)
   

