# Generated by Django 4.2 on 2023-04-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='delvreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=20)),
                ('dpass', models.CharField(blank=True, max_length=20, null=True)),
                ('demail', models.EmailField(max_length=254)),
                ('dphone', models.BigIntegerField()),
                ('dlicense', models.FileField(upload_to='')),
                ('dob', models.DateField()),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
