# Generated by Django 4.2 on 2023-05-03 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_alter_delvreg_dlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='delvreg',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
