# Generated by Django 4.2 on 2023-05-16 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0003_delvreg_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='delvreg',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
