# Generated by Django 4.2 on 2023-04-28 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upass', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=254)),
                ('uphone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('upalce', models.CharField(blank=True, max_length=20, null=True)),
                ('udist', models.CharField(blank=True, max_length=20, null=True)),
                ('upin', models.IntegerField(blank=True, max_length=6, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
