# Generated by Django 4.2 on 2023-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='upin',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
