# Generated by Django 4.2 on 2023-05-16 04:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_alter_userreg_upin'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreg',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
