# Generated by Django 4.2 on 2023-05-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_remove_cart_item_remove_cart_user_cart_menuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restid',
        ),
    ]
