# Generated by Django 4.2 on 2023-05-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0014_restreg_joindate'),
        ('userapp', '0008_alter_cart_menuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.restreg'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='menuid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.menu'),
        ),
    ]
