# Generated by Django 4.2 on 2023-06-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userapp", "0009_cart_restid_alter_cart_menuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="payment_status",
            field=models.BooleanField(default=False),
        ),
    ]
