# Generated by Django 4.2.1 on 2023-06-07 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cartid',
            field=models.ManyToManyField(to='userapp.cart'),
        ),
        migrations.CreateModel(
            name='Checkoutadd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addname', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=20)),
                ('dist', models.CharField(max_length=20)),
                ('pin', models.IntegerField()),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.userreg')),
            ],
        ),
    ]
