# Generated by Django 4.2.1 on 2023-06-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_order_cartid_checkoutadd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutadd',
            old_name='dist',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='checkoutadd',
            name='place',
        ),
        migrations.AddField(
            model_name='checkoutadd',
            name='fulladdress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='checkoutadd',
            name='landmark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
