# Generated by Django 4.2.1 on 2023-06-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_rename_dist_checkoutadd_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreg',
            old_name='udist',
            new_name='addname',
        ),
        migrations.RenameField(
            model_name='userreg',
            old_name='upalce',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userreg',
            name='upin',
        ),
        migrations.AddField(
            model_name='userreg',
            name='fulladdress',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userreg',
            name='landmark',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
