# Generated by Django 4.2.1 on 2023-06-10 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_userreg_upin'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='adrid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.checkoutadd'),
        ),
        migrations.AlterField(
            model_name='checkoutadd',
            name='location',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
