# Generated by Django 4.2 on 2023-04-28 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restreg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restname', models.CharField(max_length=20)),
                ('restpass', models.CharField(blank=True, max_length=20, null=True)),
                ('restemail', models.EmailField(max_length=254)),
                ('restphone', models.BigIntegerField()),
                ('restlicense', models.FileField(upload_to='restlicense')),
                ('restpalce', models.CharField(max_length=20)),
                ('restdist', models.CharField(max_length=20)),
                ('restpin', models.IntegerField(max_length=6)),
                ('opentime', models.CharField(max_length=20)),
                ('closetime', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
