# Generated by Django 4.2 on 2023-04-28 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restreg',
            old_name='restpalce',
            new_name='restplace',
        ),
    ]
