# Generated by Django 4.2 on 2023-05-03 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0002_rename_restpalce_restreg_restplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='restreg',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
