# Generated by Django 4.2 on 2023-05-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0003_restreg_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='restreg',
            name='restrating',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
