# Generated by Django 4.2 on 2023-05-05 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0005_category_menu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='type',
            new_name='itype',
        ),
        migrations.AlterField(
            model_name='restreg',
            name='restpin',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='restreg',
            name='restrating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
