# Generated by Django 4.2 on 2023-05-15 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0010_alter_restreg_restname'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='restid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapp.restreg'),
        ),
    ]
