# Generated by Django 4.2 on 2023-05-16 04:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0013_category_restid'),
    ]

    operations = [
        migrations.AddField(
            model_name='restreg',
            name='joindate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
