# Generated by Django 4.2 on 2023-05-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapp', '0014_restreg_joindate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='idesc',
            field=models.CharField(max_length=200),
        ),
    ]
